name: embox

services:
  backend:
    build: ./backend
    image: backend
    ports:
      - 8443:8443
    environment:
      - DB_URL=mongodb://db:27017
    depends_on:
      - db
  db:
    image: mongo:4.0.28-xenial
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
volumes:
  db_data: